### ISSUE TITLE
By Letter Should Roll Over to the Next Line

### ISSUE THREAD

**Issue by tgockel** [saxonparker/blockify#5]
Using the `-l` option should roll over between lines:

`/blockify -l :printer::lookwhatyoumademedo::knife::partygopher::taco::parrotmustache: These should keep going between lines`

results in the following output:

![screenshot_20190225_171804](https://user-images.githubusercontent.com/386039/53378022-630cd480-3921-11e9-8bd4-1e70eba9b31b.png)

I would expect the mustachioed parrot to begin the word "should" instead of resetting to the printer icon. It would look much better if this was altered.

**Comment by saxonparker** [comment]
done
